/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef AUTO_PSHADER_H_
# define AUTO_PSHADER_H_

const char *pshader_glsl =
 "#version 120\n"
 "uniform float u_time,u_alpha;"
 "uniform int u_x,u_y,u_z;\n"
 "#define WIDTH 800\n"
 "#define HEIGHT 600\n"
 "#define PI 3.141592\n"
 "#define MAX_ITER 255\n"
 "#define MAX_DIST 100.0\n"
 "#define EPSILON 0.0001\n"
 "#define OMEGA 1.2\n"
 "#define WH vec2(WIDTH,HEIGHT)\n"
 "mat3 n(float v)"
 "{"
   "float y=cos(v),f=sin(v);"
   "return mat3(vec3(1,0,0),vec3(0,y,-f),vec3(0,f,y));"
 "}"
 "mat3 m(float v)"
 "{"
   "float f=cos(v),y=sin(v);"
   "return mat3(vec3(f,0,y),vec3(0,1,0),vec3(-y,0,f));"
 "}"
 "mat3 s(float v)"
 "{"
   "float f=cos(v),y=sin(v);"
   "return mat3(vec3(f,-y,0),vec3(y,f,0),vec3(0,0,1));"
 "}"
 "float m(vec3 v,float m)"
 "{"
   "return length(v)-m;"
 "}"
 "float e(vec3 v)"
 "{"
   "return max(max(v.x,v.y),v.z);"
 "}"
 "float e(vec3 v,vec3 m)"
 "{"
   "return e(abs(v)-m);"
 "}"
 "float n(vec3 v,vec2 m)"
 "{"
   "vec2 f=vec2(length(v.xz)-m.x,v.y);"
   "return length(f)-m.y;"
 "}"
 "float s(float v,float f)"
 "{"
   "return min(v,f);"
 "}"
 "float f(float m,float v)"
 "{"
   "return max(-m,v);"
 "}"
 "float t(float v,float f)"
 "{"
   "return max(v,f);"
 "}"
 "float e(float v,float f,float m)"
 "{"
   "float y=min(v,f);"
   "if(v<m&&f<m)"
     "return min(y,m-sqrt((m-v)*(m-v)+(m-f)*(m-f)));"
   "else"
     " return y;"
 "}\n"
 "#define Repeat(p,c)mod(p,c)-0.5*c\n"
 "float f(vec3 v)"
 "{"
   "float f=n(v,vec2(cos(sin(u_time))*2,.1));"
   "return min(f,m(v,.3));"
 "}"
 "float v(vec3 v,vec3 m)"
 "{"
   "float r=0.;"
   "for(int y=0;y<MAX_ITER;y++)"
     "{"
       "float n=f(v+r*m);"
       "if(n<EPSILON)"
         "return r;"
       "r+=n;"
       "if(r>=MAX_DIST)"
         "break;"
     "}"
   "return MAX_DIST;"
 "}"
 "vec3 x(float v,vec2 m)"
 "{"
   "vec2 f=gl_FragCoord.xy-m/2.;"
   "float y=m.y/tan(radians(v)/2.);"
   "return normalize(vec3(f,-y));"
 "}"
 "vec3 t(vec3 v)"
 "{"
   "return normalize(vec3(f(vec3(v.x+EPSILON,v.y,v.z))-f(vec3(v.x-EPSILON,v.y,v.z)),f(vec3(v.x,v.y+EPSILON,v.z))-f(vec3(v.x,v.y-EPSILON,v.z)),f(vec3(v.x,v.y,v.z+EPSILON))-f(vec3(v.x,v.y,v.z-EPSILON))));"
 "}"
 "mat4 f(vec3 v,vec3 m,vec3 f)"
 "{"
   "vec3 y=normalize(m-v),u=normalize(cross(y,f)),x=cross(u,y);"
   "return mat4(vec4(u,0.),vec4(x,0.),vec4(-y,0.),vec4(0.,0.,0.,1));"
 "}"
 "vec3 v(vec3 v)"
 "{"
   "return v.y=max(v.y,0.),vec3(pow(1.-v.y,2.),1.-v.y,.6+(1.-v.y)*.4);"
 "}"
 "vec3 e(vec3 v,vec3 m,float f,vec3 y,vec3 x,vec3 u,vec3 e)"
 "{"
   "vec3 z=t(y),r=normalize(u-y),c=normalize(x-y),p=normalize(reflect(-r,z));"
   "float n=dot(r,z),N=dot(p,c);"
   "if(n<0.)"
     "return vec3(0.,0.,0.);"
   "if(N<0.)"
     "return e*(v*n);"
   "return e*(v*n+m*pow(N,f));"
 "}"
 "vec3 e(vec3 v,vec3 f,vec3 y,float m,vec3 x,vec3 u)"
 "{"
   "const vec3 n=.2*vec3(1.,1.,1.);"
   "vec3 r=n*v,N=vec3(4.*sin(u_time)*3,2.,4.*cos(u_time))*3,z=vec3(.4,.4,.4);"
   "r+=e(f,y,m,x,u,N,z);"
   "vec3 c=vec3(2.*sin(.37*u_time)*3,2.*cos(.37*u_time)*3,2.),T=vec3(.4,.4,.4);"
   "r+=e(f,y,m,x,u,c,T);"
   "return r;"
 "}"
 "void main()"
 "{"
   "vec2 m=gl_FragCoord.xy/WH;"
   "m=m*2.-1.;"
   "m.x*=WIDTH/HEIGHT;"
   "vec3 y=x(45.,WH),u=vec3(8.,5.,1.);"
   "mat4 r=f(u,vec3(u_x,u_y,u_z),vec3(0.,1.,0.));"
   "vec3 z=(r*vec4(y,0.)).xyz;"
   "float n=v(u,z);"
   "vec3 c=normalize(vec3(m.xy,-2.));"
   "c.z+=length(m)*.15;"
   "if(n>MAX_DIST-EPSILON)"
     "{"
       "gl_FragColor=vec4(v(c)-u_alpha,0.);"
       "return;"
     "}"
   "vec3 N=u+n*z,p=vec3(.2,.2,.2),T=vec3(.7,.2,.2),a=vec3(1.,1.,1.);"
   "float H=10.;"
   "vec3 l=e(p,T,a,H,N,u);"
   "gl_FragColor=vec4(l-u_alpha,1.);"
 "}";

#endif // AUTO_PSHADER_H_
